const entireCatalog = [
    { id: 1, songName: "Innovative", duration: 248, genre: "Rock" },
    {
      id: 2,
      songName: "asymmetric",
      duration: 568,
      genre: "Sould"
    },
    { id: 3, songName: "cohesive", duration: 395, genre: "Rock" },
    { id: 4, songName: "intangible", duration: 256, genre: "Funk" },
    { id: 5, songName: "systematic", duration: 246, genre: "Techno" },
    { id: 6, songName: "coherent", duration: 308, genre: "Rock" },
    { id: 7, songName: "intranet", duration: 516, genre: "Rock" },
    { id: 8, songName: "utilisation", duration: 351, genre: "Rock" },
    { id: 9, songName: "database", duration: 535, genre: "Blues" },
    { id: 10, songName: "knowledge base", duration: 596, genre: "Jazz" },
    { id: 11, songName: "incremental", duration: 457, genre: "Americana" },
    {
      id: 12,
      songName: "Multi-channelled",
      duration: 338,
      genre: "Pop"
    },
    { id: 13, songName: "Ameliorated", duration: 500, genre: "Techno" },
    { id: 14, songName: "multimedia", duration: 285, genre: "Funk" },
    { id: 15, songName: "conglomeration", duration: 303, genre: "Rock" },
    { id: 16, songName: "capacity", duration: 280, genre: "Country" },
    { id: 17, songName: "Inverse", duration: 550, genre: "EDM" },
    {
      id: 18,
      songName: "infrastructure",
      duration: 270,
      genre: "Sould"
    },
    { id: 19, songName: "Enhanced", duration: 491, genre: "Country" },
    { id: 20, songName: "dedicated", duration: 259, genre: "Rock" },
    {
      id: 21,
      songName: "Face to face",
      duration: 494,
      genre: "Blues"
    },
    { id: 22, songName: "Configurable", duration: 531, genre: "Classical" },
    { id: 23, songName: "user-facing", duration: 309, genre: "Rock" },
    { id: 24, songName: "solution", duration: 506, genre: "Funk" },
    { id: 25, songName: "analyzer", duration: 566, genre: "Rock" },
    { id: 26, songName: "Customizable", duration: 359, genre: "Funk" },
    { id: 27, songName: "mobile", duration: 321, genre: "Rock" },
    { id: 28, songName: "5th generation", duration: 395, genre: "Jazz" },
    { id: 29, songName: "client-driven", duration: 356, genre: "EDM" },
    { id: 30, songName: "customer loyalty", duration: 270, genre: "Rock" },
    { id: 31, songName: "Front-line", duration: 308, genre: "Pop" },
    {
      id: 32,
      songName: "multimedia",
      duration: 537,
      genre: "Blues"
    },
    { id: 33, songName: "service-desk", duration: 300, genre: "Rock" },
    { id: 34, songName: "Sharable", duration: 510, genre: "Rock" },
    { id: 35, songName: "dedicated", duration: 470, genre: "Country" },
    { id: 36, songName: "leverage", duration: 433, genre: "Rock" },
    { id: 37, songName: "Team-oriented", duration: 320, genre: "Country" },
    { id: 38, songName: "hub", duration: 420, genre: "Metal" },
    { id: 39, songName: "analyzer", duration: 380, genre: "Rock" },
    { id: 40, songName: "Phased", duration: 329, genre: "Pop" },
    { id: 41, songName: "multimedia", duration: 560, genre: "Techno" },
    {
      id: 42,
      songName: "Extended",
      duration: 325,
      genre: "Sould"
    },
    { id: 43, songName: "data-warehouse", duration: 437, genre: "Rock" },
    { id: 44, songName: "high-level", duration: 242, genre: "Dance" },
    { id: 45, songName: "Multi-layered", duration: 293, genre: "Rock" },
    {
      id: 46,
      songName: "monitoring",
      duration: 352,
      genre: "Blues"
    },
    { id: 47, songName: "standardization", duration: 368, genre: "Rock" },
    { id: 48, songName: "Phased", duration: 271, genre: "Rock" },
    { id: 49, songName: "firmware", duration: 262, genre: "Rock" },
    { id: 50, songName: "human-resource", duration: 548, genre: "Rock" },
    { id: 51, songName: "intangible", duration: 553, genre: "Dance" },
    { id: 52, songName: "zero defect", duration: 254, genre: "Rock" },
    { id: 53, songName: "Organized", duration: 263, genre: "Rock" },
    { id: 54, songName: "orchestration", duration: 590, genre: "Rock" },
    { id: 55, songName: "framework", duration: 378, genre: "Rock" },
    { id: 56, songName: "high-level", duration: 587, genre: "Rock" },
    { id: 57, songName: "Synergized", duration: 581, genre: "Rock" },
    { id: 58, songName: "asymmetric", duration: 261, genre: "Funk" },
    { id: 59, songName: "Total", duration: 354, genre: "Pop" },
    { id: 60, songName: "explicit", duration: 278, genre: "Rock" },
    { id: 61, songName: "upward-trending", duration: 283, genre: "Dance" },
    {
      id: 62,
      songName: "Exclusive",
      duration: 236,
      genre: "diners-club-international"
    },
    { id: 63, songName: "intangible", duration: 390, genre: "Classical" },
    { id: 64, songName: "Automated", duration: 446, genre: "Classical" },
    { id: 65, songName: "composite", duration: 331, genre: "Rock" },
    { id: 66, songName: "optimal", duration: 302, genre: "Metal" },
    { id: 67, songName: "regional", duration: 351, genre: "Rock" },
    { id: 68, songName: "Synergized", duration: 480, genre: "Americana" },
    { id: 69, songName: "Integrated", duration: 233, genre: "Bluegrass" },
    { id: 70, songName: "forecast", duration: 479, genre: "Country" },
    { id: 71, songName: "dynamic", duration: 266, genre: "Blues" },
    { id: 72, songName: "Balanced", duration: 567, genre: "Rock" },
    { id: 73, songName: "knowledge base", duration: 248, genre: "Techno" },
    {
      id: 74,
      songName: "Synchronised",
      duration: 425,
      genre: "Blues"
    },
    { id: 75, songName: "Open-source", duration: 346, genre: "Dance" },
    { id: 76, songName: "approach", duration: 438, genre: "Pop" },
    { id: 77, songName: "multi-tasking", duration: 356, genre: "Bluegrass" },
    { id: 78, songName: "project", duration: 345, genre: "Blues" },
    { id: 79, songName: "protocol", duration: 232, genre: "Rock" },
    { id: 80, songName: "context-sensitive", duration: 406, genre: "Funk" },
    {
      id: 81,
      songName: "implementation",
      duration: 340,
      genre: "EDM"
    },
    { id: 82, songName: "scalable", duration: 525, genre: "Rock" },
    { id: 83, songName: "knowledge base", duration: 407, genre: "Bluegrass" },
    { id: 84, songName: "interface", duration: 486, genre: "Rock" },
    { id: 85, songName: "toolset", duration: 345, genre: "Techno" },
    { id: 86, songName: "Progressive", duration: 509, genre: "Techno" },
    { id: 87, songName: "mission-critical", duration: 377, genre: "Techno" },
    { id: 88, songName: "task-force", duration: 235, genre: "Funk" },
    { id: 89, songName: "Down-sized", duration: 501, genre: "Techno" },
    { id: 90, songName: "grid-enabled", duration: 511, genre: "Bluegrass" },
    { id: 91, songName: "circuit", duration: 458, genre: "Country" },
    { id: 92, songName: "software", duration: 431, genre: "Americana" },
    { id: 93, songName: "Decentralized", duration: 272, genre: "Bluegrass" },
    { id: 94, songName: "empowering", duration: 240, genre: "Classical" },
    { id: 95, songName: "coherent", duration: 434, genre: "Funk" },
    { id: 96, songName: "User-friendly", duration: 455, genre: "Rock" },
    { id: 97, songName: "Diverse", duration: 258, genre: "Jazz" },
    { id: 98, songName: "Enterprise-wide", duration: 420, genre: "Rock" },
    { id: 99, songName: "Universal", duration: 233, genre: "Americana" },
    { id: 100, songName: "bandwidth-monitored", duration: 418, genre: "Rock" },
    { id: 101, songName: "Operative", duration: 271, genre: "Rock" },
    { id: 102, songName: "De-engineered", duration: 588, genre: "Funk" },
    { id: 103, songName: "Configurable", duration: 233, genre: "Rock" },
    { id: 104, songName: "Organic", duration: 341, genre: "Funk" },
    {
      id: 105,
      songName: "asymmetric",
      duration: 378,
      genre: "Sould"
    },
    { id: 106, songName: "Organized", duration: 258, genre: "Rock" },
    { id: 107, songName: "Versatile", duration: 415, genre: "Rock" },
    { id: 108, songName: "motivating", duration: 573, genre: "Jazz" },
    { id: 109, songName: "hardware", duration: 406, genre: "Rock" },
    { id: 110, songName: "adapter", duration: 321, genre: "Techno" },
    {
      id: 111,
      songName: "customer loyalty",
      duration: 239,
      genre: "Blues"
    },
    { id: 112, songName: "framework", duration: 568, genre: "Rock" },
    { id: 113, songName: "portal", duration: 403, genre: "Rock" },
    { id: 114, songName: "stable", duration: 328, genre: "Techno" },
    { id: 115, songName: "holistic", duration: 544, genre: "Rock" },
    { id: 116, songName: "maximized", duration: 519, genre: "Rock" },
    { id: 117, songName: "methodical", duration: 296, genre: "Country" },
    { id: 118, songName: "exuding", duration: 291, genre: "Rock" },
    { id: 119, songName: "6th generation", duration: 495, genre: "Dance" },
    { id: 120, songName: "human-resource", duration: 562, genre: "Techno" },
    { id: 121, songName: "human-resource", duration: 505, genre: "Classical" },
    {
      id: 122,
      songName: "didactic",
      duration: 286,
      genre: "Sould"
    },
    { id: 123, songName: "responsive", duration: 261, genre: "Country" },
    { id: 124, songName: "Public-key", duration: 331, genre: "Americana" },
    { id: 125, songName: "local area network", duration: 355, genre: "Techno" },
    { id: 126, songName: "Optional", duration: 432, genre: "Techno" },
    {
      id: 127,
      songName: "multi-tasking",
      duration: 330,
      genre: "Sould"
    },
    { id: 128, songName: "Optional", duration: 352, genre: "Pop" },
    { id: 129, songName: "responsive", duration: 264, genre: "Americana" },
    { id: 130, songName: "Persistent", duration: 562, genre: "Country" },
    { id: 131, songName: "productivity", duration: 579, genre: "Rock" },
    { id: 132, songName: "background", duration: 428, genre: "Rock" },
    { id: 133, songName: "methodology", duration: 272, genre: "Rock" },
    { id: 134, songName: "Implemented", duration: 435, genre: "Country" },
    { id: 135, songName: "encompassing", duration: 385, genre: "Rock" },
    { id: 136, songName: "24 hour", duration: 559, genre: "Americana" },
    { id: 137, songName: "interface", duration: 485, genre: "Metal" },
    { id: 138, songName: "function", duration: 265, genre: "Rock" },
    { id: 139, songName: "full-range", duration: 308, genre: "Techno" },
    { id: 140, songName: "matrix", duration: 498, genre: "Rock" },
    { id: 141, songName: "database", duration: 287, genre: "Pop" },
    { id: 142, songName: "product", duration: 314, genre: "Bluegrass" },
    { id: 143, songName: "bifurcated", duration: 400, genre: "Pop" },
    { id: 144, songName: "heuristic", duration: 297, genre: "Funk" },
    { id: 145, songName: "knowledge user", duration: 542, genre: "Rock" },
    { id: 146, songName: "needs-based", duration: 253, genre: "Rock" },
    {
      id: 147,
      songName: "Automated",
      duration: 545,
      genre: "Sould"
    },
    { id: 148, songName: "Grass-roots", duration: 574, genre: "Rock" },
    { id: 149, songName: "Assimilated", duration: 556, genre: "Rock" },
    { id: 150, songName: "hybrid", duration: 437, genre: "Rock" },
    { id: 151, songName: "hub", duration: 297, genre: "Pop" },
    { id: 152, songName: "User-friendly", duration: 559, genre: "Funk" },
    {
      id: 153,
      songName: "success",
      duration: 359,
      genre: "Sould"
    },
    { id: 154, songName: "array", duration: 361, genre: "EDM" },
    { id: 155, songName: "conglomeration", duration: 520, genre: "Rock" },
    { id: 156, songName: "Quality-focused", duration: 254, genre: "Rock" },
    {
      id: 157,
      songName: "Upgradable",
      duration: 331,
      genre: "Blues"
    },
    { id: 158, songName: "frame", duration: 289, genre: "Techno" },
    { id: 159, songName: "matrices", duration: 560, genre: "Rock" },
    { id: 160, songName: "Phased", duration: 281, genre: "Dance" },
    { id: 161, songName: "optimal", duration: 572, genre: "Rock" },
    { id: 162, songName: "Streamlined", duration: 539, genre: "Techno" },
    { id: 163, songName: "Reverse-engineered", duration: 420, genre: "Country" },
    { id: 164, songName: "Up-sized", duration: 371, genre: "Rock" },
    { id: 165, songName: "mobile", duration: 269, genre: "Country" },
    {
      id: 166,
      songName: "Programmable",
      duration: 291,
      genre: "Pop"
    },
    { id: 167, songName: "Stand-alone", duration: 575, genre: "Pop" },
    { id: 168, songName: "logistical", duration: 599, genre: "Techno" },
    { id: 169, songName: "tangible", duration: 469, genre: "Funk" },
    { id: 170, songName: "solution", duration: 246, genre: "Rock" },
    { id: 171, songName: "parallelism", duration: 275, genre: "Rock" },
    { id: 172, songName: "client-driven", duration: 488, genre: "Rock" },
    { id: 173, songName: "non-volatile", duration: 452, genre: "Rock" },
    { id: 174, songName: "capacity", duration: 481, genre: "Rock" },
    { id: 175, songName: "workforce", duration: 529, genre: "Rock" },
    { id: 176, songName: "info-mediaries", duration: 271, genre: "Jazz" },
    { id: 177, songName: "collaboration", duration: 274, genre: "Rock" },
    { id: 178, songName: "Vision-oriented", duration: 556, genre: "Rock" },
    { id: 179, songName: "asymmetric", duration: 471, genre: "Techno" },
    { id: 180, songName: "Public-key", duration: 405, genre: "EDM" },
    { id: 181, songName: "Down-sized", duration: 293, genre: "Pop" },
    { id: 182, songName: "Sharable", duration: 253, genre: "Classical" },
    { id: 183, songName: "encoding", duration: 490, genre: "Pop" },
    { id: 184, songName: "strategy", duration: 506, genre: "Rock" },
    { id: 185, songName: "interface", duration: 354, genre: "EDM" },
    { id: 186, songName: "coherent", duration: 396, genre: "Country" },
    { id: 187, songName: "foreground", duration: 401, genre: "Jazz" },
    { id: 188, songName: "Re-engineered", duration: 573, genre: "Jazz" },
    { id: 189, songName: "complexity", duration: 462, genre: "Country" },
    {
      id: 190,
      songName: "client-server",
      duration: 561,
      genre: "Pop"
    },
    { id: 191, songName: "Right-sized", duration: 372, genre: "Pop" },
    { id: 192, songName: "tertiary", duration: 555, genre: "Metal" },
    { id: 193, songName: "cohesive", duration: 558, genre: "Rock" },
    { id: 194, songName: "regional", duration: 595, genre: "Rock" },
    { id: 195, songName: "content-based", duration: 299, genre: "Techno" },
    { id: 196, songName: "multi-tasking", duration: 324, genre: "Jazz" },
    { id: 197, songName: "impactful", duration: 552, genre: "Rock" },
    { id: 198, songName: "intranet", duration: 432, genre: "Rock" },
    { id: 199, songName: "protocol", duration: 456, genre: "Rock" },
    { id: 200, songName: "knowledge base", duration: 294, genre: "Rock" },
    { id: 201, songName: "approach", duration: 304, genre: "Techno" },
    { id: 202, songName: "intangible", duration: 291, genre: "Rock" },
    { id: 203, songName: "discrete", duration: 425, genre: "Rock" },
    { id: 204, songName: "approach", duration: 547, genre: "Rock" },
    { id: 205, songName: "non-volatile", duration: 493, genre: "Country" },
    { id: 206, songName: "Balanced", duration: 485, genre: "Rock" },
    { id: 207, songName: "algorithm", duration: 479, genre: "Bluegrass" },
    {
      id: 208,
      songName: "4th generation",
      duration: 233,
      genre: "Sould"
    },
    {
      id: 209,
      songName: "Re-contextualized",
      duration: 421,
      genre: "Funk"
    },
    { id: 210, songName: "secondary", duration: 441, genre: "Metal" },
    { id: 211, songName: "Open-architected", duration: 367, genre: "Dance" },
    { id: 212, songName: "capacity", duration: 245, genre: "Metal" },
    { id: 213, songName: "client-server", duration: 384, genre: "Rock" },
    { id: 214, songName: "focus group", duration: 400, genre: "Techno" },
    { id: 215, songName: "Realigned", duration: 299, genre: "Rock" },
    { id: 216, songName: "Horizontal", duration: 452, genre: "Rock" },
    { id: 217, songName: "modular", duration: 546, genre: "Funk" },
    { id: 218, songName: "Fundamental", duration: 528, genre: "Rock" },
    {
      id: 219,
      songName: "pricing structure",
      duration: 279,
      genre: "Blues"
    },
    { id: 220, songName: "coherent", duration: 485, genre: "Rock" },
    {
      id: 221,
      songName: "fresh-thinking",
      duration: 272,
      genre: "EDM"
    },
    { id: 222, songName: "Expanded", duration: 246, genre: "Rock" },
    { id: 223, songName: "Business-focused", duration: 243, genre: "Rock" },
    { id: 224, songName: "Mandatory", duration: 457, genre: "Rock" },
    { id: 225, songName: "frame", duration: 546, genre: "Rock" },
    { id: 226, songName: "hierarchy", duration: 476, genre: "Rock" },
    { id: 227, songName: "intermediate", duration: 458, genre: "Jazz" },
    { id: 228, songName: "Triple-buffered", duration: 509, genre: "Rock" },
    { id: 229, songName: "strategy", duration: 250, genre: "Jazz" },
    { id: 230, songName: "Re-contextualized", duration: 589, genre: "Rock" },
    { id: 231, songName: "Public-key", duration: 304, genre: "Pop" },
    { id: 232, songName: "firmware", duration: 531, genre: "Rock" },
    {
      id: 233,
      songName: "bandwidth-monitored",
      duration: 330,
      genre: "Funk"
    },
    { id: 234, songName: "uniform", duration: 234, genre: "Rock" },
    { id: 235, songName: "even-keeled", duration: 580, genre: "EDM" },
    {
      id: 236,
      songName: "encompassing",
      duration: 319,
      genre: "diners-club-us-ca"
    },
    { id: 237, songName: "Team-oriented", duration: 241, genre: "Rock" },
    { id: 238, songName: "Re-engineered", duration: 409, genre: "Americana" },
    { id: 239, songName: "Integrated", duration: 443, genre: "Rock" },
    {
      id: 240,
      songName: "Team-oriented",
      duration: 292,
      genre: "Pop"
    },
    { id: 241, songName: "standardization", duration: 593, genre: "Rock" },
    { id: 242, songName: "secured line", duration: 335, genre: "Rock" },
    { id: 243, songName: "Open-architected", duration: 454, genre: "Bluegrass" },
    { id: 244, songName: "contingency", duration: 373, genre: "Rock" },
    { id: 245, songName: "Open-source", duration: 521, genre: "Rock" },
    { id: 246, songName: "client-server", duration: 523, genre: "Rock" },
    { id: 247, songName: "Synchronised", duration: 376, genre: "EDM" },
    {
      id: 248,
      songName: "empowering",
      duration: 480,
      genre: "Blues"
    },
    { id: 249, songName: "optimal", duration: 569, genre: "Rock" },
    { id: 250, songName: "matrix", duration: 273, genre: "Rock" },
    { id: 251, songName: "product", duration: 502, genre: "Techno" },
    { id: 252, songName: "asymmetric", duration: 392, genre: "Jazz" },
    { id: 253, songName: "incremental", duration: 500, genre: "Rock" },
    { id: 254, songName: "dynamic", duration: 321, genre: "Rock" },
    { id: 255, songName: "strategy", duration: 426, genre: "Techno" },
    { id: 256, songName: "Cloned", duration: 260, genre: "Techno" },
    {
      id: 257,
      songName: "solution-oriented",
      duration: 354,
      genre: "Americana"
    },
    { id: 258, songName: "knowledge user", duration: 294, genre: "Rock" },
    { id: 259, songName: "attitude", duration: 528, genre: "Rock" },
    { id: 260, songName: "background", duration: 477, genre: "Funk" },
    { id: 261, songName: "analyzing", duration: 585, genre: "Funk" },
    {
      id: 262,
      songName: "web-enabled",
      duration: 478,
      genre: "diners-club-us-ca"
    },
    { id: 263, songName: "initiative", duration: 326, genre: "Pop" },
    { id: 264, songName: "transitional", duration: 481, genre: "Country" },
    { id: 265, songName: "optimal", duration: 374, genre: "Rock" },
    { id: 266, songName: "Object-based", duration: 337, genre: "Funk" },
    { id: 267, songName: "Universal", duration: 293, genre: "Rock" },
    { id: 268, songName: "methodology", duration: 300, genre: "Rock" },
    { id: 269, songName: "Optimized", duration: 548, genre: "Techno" },
    { id: 270, songName: "attitude-oriented", duration: 364, genre: "Rock" },
    {
      id: 271,
      songName: "capability",
      duration: 600,
      genre: "Sould"
    },
    { id: 272, songName: "homogeneous", duration: 493, genre: "Rock" },
    { id: 273, songName: "composite", duration: 500, genre: "Americana" },
    { id: 274, songName: "contingency", duration: 326, genre: "Techno" },
    { id: 275, songName: "Diverse", duration: 431, genre: "Rock" },
    { id: 276, songName: "ability", duration: 266, genre: "Rock" },
    { id: 277, songName: "zero administration", duration: 383, genre: "Rock" },
    { id: 278, songName: "Secured", duration: 242, genre: "Rock" },
    { id: 279, songName: "model", duration: 294, genre: "Rock" },
    { id: 280, songName: "model", duration: 548, genre: "EDM" },
    { id: 281, songName: "motivating", duration: 231, genre: "Rock" },
    { id: 282, songName: "interactive", duration: 575, genre: "Rock" },
    { id: 283, songName: "Assimilated", duration: 574, genre: "Funk" },
    { id: 284, songName: "Automated", duration: 314, genre: "Funk" },
    { id: 285, songName: "Virtual", duration: 593, genre: "Funk" },
    {
      id: 286,
      songName: "Graphical User Interface",
      duration: 355,
      genre: "Rock"
    },
    { id: 287, songName: "discrete", duration: 547, genre: "Rock" },
    { id: 288, songName: "Streamlined", duration: 409, genre: "Rock" },
    {
      id: 289,
      songName: "Graphical User Interface",
      duration: 456,
      genre: "Rock"
    },
    {
      id: 290,
      songName: "well-modulated",
      duration: 356,
      genre: "diners-club-us-ca"
    },
    {
      id: 291,
      songName: "system engine",
      duration: 261,
      genre: "diners-club-us-ca"
    },
    { id: 292, songName: "Multi-lateral", duration: 449, genre: "Rock" },
    { id: 293, songName: "fault-tolerant", duration: 318, genre: "Techno" },
    { id: 294, songName: "toolset", duration: 446, genre: "Rock" },
    { id: 295, songName: "value-added", duration: 599, genre: "Funk" },
    { id: 296, songName: "Total", duration: 450, genre: "Pop" },
    { id: 297, songName: "paradigm", duration: 341, genre: "Rock" },
    {
      id: 298,
      songName: "tertiary",
      duration: 575,
      genre: "diners-club-international"
    },
    { id: 299, songName: "system-worthy", duration: 552, genre: "Rock" },
    { id: 300, songName: "Balanced", duration: 341, genre: "Techno" },
    { id: 301, songName: "homogeneous", duration: 368, genre: "Techno" },
    { id: 302, songName: "motivating", duration: 428, genre: "EDM" },
    { id: 303, songName: "scalable", duration: 382, genre: "EDM" },
    { id: 304, songName: "Distributed", duration: 271, genre: "Pop" },
    { id: 305, songName: "background", duration: 548, genre: "Metal" },
    { id: 306, songName: "heuristic", duration: 330, genre: "Bluegrass" },
    { id: 307, songName: "knowledge user", duration: 545, genre: "Country" },
    { id: 308, songName: "needs-based", duration: 302, genre: "EDM" },
    { id: 309, songName: "radical", duration: 453, genre: "Rock" },
    { id: 310, songName: "service-desk", duration: 567, genre: "Americana" },
    { id: 311, songName: "Self-enabling", duration: 562, genre: "Techno" },
    { id: 312, songName: "high-level", duration: 535, genre: "EDM" },
    { id: 313, songName: "analyzer", duration: 497, genre: "Rock" },
    {
      id: 314,
      songName: "User-centric",
      duration: 255,
      genre: "Pop"
    },
    { id: 315, songName: "Switchable", duration: 576, genre: "Rock" },
    {
      id: 316,
      songName: "needs-based",
      duration: 375,
      genre: "diners-club-us-ca"
    },
    { id: 317, songName: "Digitized", duration: 555, genre: "diners-club-us-ca" },
    { id: 318, songName: "matrices", duration: 336, genre: "Americana" },
    { id: 319, songName: "migration", duration: 510, genre: "Techno" },
    { id: 320, songName: "dynamic", duration: 376, genre: "Rock" },
    { id: 321, songName: "Versatile", duration: 552, genre: "Rock" },
    {
      id: 322,
      songName: "data-warehouse",
      duration: 410,
      genre: "Americana"
    },
    { id: 323, songName: "attitude", duration: 431, genre: "Jazz" },
    { id: 324, songName: "groupware", duration: 444, genre: "Americana" },
    { id: 325, songName: "Horizontal", duration: 597, genre: "Country" },
    { id: 326, songName: "Realigned", duration: 523, genre: "Techno" },
    { id: 327, songName: "open architecture", duration: 555, genre: "Rock" },
    { id: 328, songName: "static", duration: 391, genre: "Funk" },
    { id: 329, songName: "6th generation", duration: 525, genre: "Rock" },
    { id: 330, songName: "Enhanced", duration: 246, genre: "Rock" },
    { id: 331, songName: "Networked", duration: 483, genre: "Rock" },
    { id: 332, songName: "tertiary", duration: 338, genre: "Rock" },
    { id: 333, songName: "analyzing", duration: 232, genre: "Rock" },
    { id: 334, songName: "protocol", duration: 512, genre: "Rock" },
    {
      id: 335,
      songName: "Multi-channelled",
      duration: 274,
      genre: "Blues"
    },
    { id: 336, songName: "Grass-roots", duration: 378, genre: "Classical" },
    { id: 337, songName: "Vision-oriented", duration: 410, genre: "Funk" },
    { id: 338, songName: "Enterprise-wide", duration: 323, genre: "Rock" },
    {
      id: 339,
      songName: "responsive",
      duration: 464,
      genre: "Sould"
    },
    {
      id: 340,
      songName: "budgetary management",
      duration: 328,
      genre: "Pop"
    },
    { id: 341, songName: "tangible", duration: 575, genre: "Techno" },
    { id: 342, songName: "Pre-emptive", duration: 522, genre: "Dance" },
    { id: 343, songName: "secured line", duration: 545, genre: "Rock" },
    { id: 344, songName: "Centralized", duration: 515, genre: "Rock" },
    { id: 345, songName: "User-centric", duration: 589, genre: "Rock" },
    { id: 346, songName: "software", duration: 514, genre: "Funk" },
    { id: 347, songName: "intranet", duration: 538, genre: "Pop" },
    {
      id: 348,
      songName: "systematic",
      duration: 509,
      genre: "Blues"
    },
    { id: 349, songName: "application", duration: 345, genre: "Pop" },
    { id: 350, songName: "portal", duration: 572, genre: "Rock" },
    { id: 351, songName: "Progressive", duration: 366, genre: "Techno" },
    { id: 352, songName: "discrete", duration: 487, genre: "Techno" },
    { id: 353, songName: "Intuitive", duration: 318, genre: "Funk" },
    { id: 354, songName: "Re-engineered", duration: 541, genre: "Rock" },
    { id: 355, songName: "high-level", duration: 360, genre: "Rock" },
    { id: 356, songName: "Object-based", duration: 359, genre: "Rock" },
    { id: 357, songName: "5th generation", duration: 383, genre: "Dance" },
    {
      id: 358,
      songName: "full-range",
      duration: 274,
      genre: "Blues"
    },
    { id: 359, songName: "Robust", duration: 325, genre: "diners-club-us-ca" },
    { id: 360, songName: "structure", duration: 600, genre: "Metal" },
    { id: 361, songName: "Switchable", duration: 582, genre: "Funk" },
    { id: 362, songName: "Multi-tiered", duration: 249, genre: "Americana" },
    { id: 363, songName: "stable", duration: 593, genre: "Rock" },
    { id: 364, songName: "actuating", duration: 285, genre: "Rock" },
    { id: 365, songName: "data-warehouse", duration: 487, genre: "Rock" },
    { id: 366, songName: "bifurcated", duration: 389, genre: "Funk" },
    { id: 367, songName: "benchmark", duration: 250, genre: "Funk" },
    { id: 368, songName: "User-centric", duration: 589, genre: "Rock" },
    { id: 369, songName: "benchmark", duration: 476, genre: "Techno" },
    {
      id: 370,
      songName: "service-desk",
      duration: 394,
      genre: "Pop"
    },
    { id: 371, songName: "Expanded", duration: 551, genre: "Bluegrass" },
    { id: 372, songName: "Future-proofed", duration: 507, genre: "Rock" },
    { id: 373, songName: "Intuitive", duration: 436, genre: "Dance" },
    { id: 374, songName: "benchmark", duration: 422, genre: "Americana" },
    { id: 375, songName: "paradigm", duration: 338, genre: "Techno" },
    { id: 376, songName: "time-frame", duration: 358, genre: "Pop" },
    { id: 377, songName: "static", duration: 435, genre: "Rock" },
    { id: 378, songName: "system-worthy", duration: 314, genre: "Rock" },
    { id: 379, songName: "neural-net", duration: 388, genre: "Rock" },
    {
      id: 380,
      songName: "attitude-oriented",
      duration: 450,
      genre: "diners-club-us-ca"
    },
    { id: 381, songName: "Front-line", duration: 289, genre: "Rock" },
    { id: 382, songName: "solution", duration: 463, genre: "Rock" },
    { id: 383, songName: "toolset", duration: 374, genre: "Rock" },
    {
      id: 384,
      songName: "optimizing",
      duration: 428,
      genre: "diners-club-us-ca"
    },
    { id: 385, songName: "Polarised", duration: 350, genre: "Rock" },
    { id: 386, songName: "Diverse", duration: 448, genre: "Rock" },
    { id: 387, songName: "Synchronised", duration: 556, genre: "Metal" },
    { id: 388, songName: "neutral", duration: 416, genre: "Jazz" },
    { id: 389, songName: "Stand-alone", duration: 594, genre: "Jazz" },
    { id: 390, songName: "clear-thinking", duration: 485, genre: "Bluegrass" },
    { id: 391, songName: "hub", duration: 552, genre: "Rock" },
    { id: 392, songName: "Re-engineered", duration: 464, genre: "Dance" },
    { id: 393, songName: "architecture", duration: 403, genre: "Metal" },
    { id: 394, songName: "Realigned", duration: 514, genre: "Rock" },
    { id: 395, songName: "web-enabled", duration: 260, genre: "Rock" },
    { id: 396, songName: "internet solution", duration: 560, genre: "Jazz" },
    {
      id: 397,
      songName: "Vision-oriented",
      duration: 372,
      genre: "diners-club-us-ca"
    },
    { id: 398, songName: "dedicated", duration: 399, genre: "Rock" },
    { id: 399, songName: "Compatible", duration: 557, genre: "Jazz" },
    { id: 400, songName: "Expanded", duration: 449, genre: "Dance" },
    { id: 401, songName: "Right-sized", duration: 510, genre: "Techno" },
    { id: 402, songName: "middleware", duration: 291, genre: "Rock" },
    { id: 403, songName: "Realigned", duration: 453, genre: "Rock" },
    { id: 404, songName: "system-worthy", duration: 553, genre: "Dance" },
    { id: 405, songName: "client-server", duration: 347, genre: "Country" },
    { id: 406, songName: "encryption", duration: 272, genre: "Americana" },
    { id: 407, songName: "solution", duration: 557, genre: "Jazz" },
    { id: 408, songName: "Operative", duration: 571, genre: "Rock" },
    { id: 409, songName: "regional", duration: 230, genre: "Pop" },
    {
      id: 410,
      songName: "strategy",
      duration: 369,
      genre: "Sould"
    },
    { id: 411, songName: "matrix", duration: 317, genre: "Americana" },
    { id: 412, songName: "Monitored", duration: 346, genre: "Rock" },
    { id: 413, songName: "software", duration: 415, genre: "Rock" },
    { id: 414, songName: "exuding", duration: 308, genre: "Funk" },
    {
      id: 415,
      songName: "high-level",
      duration: 243,
      genre: "Sould"
    },
    { id: 416, songName: "Operative", duration: 461, genre: "Rock" },
    { id: 417, songName: "Organized", duration: 442, genre: "Rock" },
    { id: 418, songName: "circuit", duration: 476, genre: "Rock" },
    { id: 419, songName: "Mandatory", duration: 435, genre: "Country" },
    { id: 420, songName: "secured line", duration: 335, genre: "Classical" },
    { id: 421, songName: "knowledge user", duration: 371, genre: "Bluegrass" },
    { id: 422, songName: "empowering", duration: 339, genre: "Pop" },
    { id: 423, songName: "monitoring", duration: 568, genre: "Country" },
    { id: 424, songName: "Persistent", duration: 536, genre: "Techno" },
    { id: 425, songName: "tangible", duration: 329, genre: "Rock" },
    { id: 426, songName: "Customer-focused", duration: 577, genre: "Rock" },
    { id: 427, songName: "concept", duration: 473, genre: "Country" },
    { id: 428, songName: "Grass-roots", duration: 540, genre: "Metal" },
    { id: 429, songName: "actuating", duration: 429, genre: "Pop" },
    { id: 430, songName: "Robust", duration: 253, genre: "Dance" },
    { id: 431, songName: "conglomeration", duration: 419, genre: "Bluegrass" },
    {
      id: 432,
      songName: "intranet",
      duration: 454,
      genre: "Sould"
    },
    { id: 433, songName: "Visionary", duration: 244, genre: "Classical" },
    { id: 434, songName: "forecast", duration: 388, genre: "Rock" },
    { id: 435, songName: "systematic", duration: 266, genre: "EDM" },
    { id: 436, songName: "web-enabled", duration: 577, genre: "Rock" },
    { id: 437, songName: "Right-sized", duration: 522, genre: "Rock" },
    {
      id: 438,
      songName: "Function-based",
      duration: 308,
      genre: "Blues"
    },
    {
      id: 439,
      songName: "access",
      duration: 559,
      genre: "Sould"
    },
    {
      id: 440,
      songName: "Down-sized",
      duration: 302,
      genre: "Sould"
    },
    { id: 441, songName: "success", duration: 448, genre: "Rock" },
    { id: 442, songName: "web-enabled", duration: 569, genre: "Funk" },
    { id: 443, songName: "Ameliorated", duration: 266, genre: "EDM" },
    { id: 444, songName: "optimal", duration: 314, genre: "Rock" },
    { id: 445, songName: "frame", duration: 246, genre: "Country" },
    { id: 446, songName: "Fully-configurable", duration: 352, genre: "Rock" },
    { id: 447, songName: "dedicated", duration: 230, genre: "Dance" },
    { id: 448, songName: "background", duration: 557, genre: "Rock" },
    { id: 449, songName: "Quality-focused", duration: 264, genre: "Rock" },
    { id: 450, songName: "matrices", duration: 399, genre: "Rock" },
    { id: 451, songName: "hardware", duration: 358, genre: "Rock" },
    { id: 452, songName: "standardization", duration: 267, genre: "Rock" },
    {
      id: 453,
      songName: "throughput",
      duration: 394,
      genre: "Sould"
    },
    { id: 454, songName: "success", duration: 503, genre: "Rock" },
    { id: 455, songName: "adapter", duration: 591, genre: "Rock" },
    {
      id: 456,
      songName: "Graphical User Interface",
      duration: 244,
      genre: "Bluegrass"
    },
    { id: 457, songName: "mission-critical", duration: 587, genre: "Funk" },
    { id: 458, songName: "budgetary management", duration: 538, genre: "Rock" },
    { id: 459, songName: "homogeneous", duration: 289, genre: "Country" },
    { id: 460, songName: "Automated", duration: 597, genre: "Americana" },
    { id: 461, songName: "Switchable", duration: 345, genre: "Rock" },
    { id: 462, songName: "local", duration: 576, genre: "Blues" },
    { id: 463, songName: "functionalities", duration: 456, genre: "Metal" },
    { id: 464, songName: "hierarchy", duration: 443, genre: "Rock" },
    { id: 465, songName: "Front-line", duration: 515, genre: "Rock" },
    { id: 466, songName: "matrix", duration: 269, genre: "Rock" },
    { id: 467, songName: "Open-architected", duration: 461, genre: "Techno" },
    { id: 468, songName: "Proactive", duration: 551, genre: "Rock" },
    { id: 469, songName: "bottom-line", duration: 288, genre: "Rock" },
    { id: 470, songName: "Synchronised", duration: 231, genre: "Funk" },
    { id: 471, songName: "Programmable", duration: 552, genre: "Rock" },
    { id: 472, songName: "Optimized", duration: 481, genre: "Rock" },
    { id: 473, songName: "forecast", duration: 406, genre: "Rock" },
    { id: 474, songName: "Advanced", duration: 253, genre: "Jazz" },
    { id: 475, songName: "contingency", duration: 562, genre: "Rock" },
    { id: 476, songName: "mission-critical", duration: 469, genre: "Rock" },
    { id: 477, songName: "Progressive", duration: 293, genre: "Techno" },
    { id: 478, songName: "multi-tasking", duration: 384, genre: "Jazz" },
    {
      id: 479,
      songName: "Stand-alone",
      duration: 428,
      genre: "Blues"
    },
    { id: 480, songName: "instruction set", duration: 349, genre: "Rock" },
    { id: 481, songName: "interactive", duration: 515, genre: "Country" },
    { id: 482, songName: "hardware", duration: 231, genre: "Jazz" },
    { id: 483, songName: "hybrid", duration: 240, genre: "Jazz" },
    { id: 484, songName: "Visionary", duration: 486, genre: "EDM" },
    { id: 485, songName: "Ameliorated", duration: 276, genre: "Rock" },
    { id: 486, songName: "database", duration: 534, genre: "Rock" },
    { id: 487, songName: "global", duration: 255, genre: "Rock" },
    { id: 488, songName: "reciprocal", duration: 269, genre: "Funk" },
    { id: 489, songName: "mission-critical", duration: 433, genre: "Rock" },
    { id: 490, songName: "Robust", duration: 397, genre: "Dance" },
    {
      id: 491,
      songName: "grid-enabled",
      duration: 435,
      genre: "Blues"
    },
    { id: 492, songName: "Assimilated", duration: 349, genre: "Techno" },
    { id: 493, songName: "standardization", duration: 497, genre: "Dance" },
    {
      id: 494,
      songName: "artificial intelligence",
      duration: 369,
      genre: "Rock"
    },
    { id: 495, songName: "Programmable", duration: 421, genre: "Techno" },
    {
      id: 496,
      songName: "coherent",
      duration: 256,
      genre: "Sould"
    },
    { id: 497, songName: "grid-enabled", duration: 464, genre: "Rock" },
    { id: 498, songName: "encoding", duration: 462, genre: "Rock" },
    { id: 499, songName: "next generation", duration: 596, genre: "Rock" },
    {
      id: 500,
      songName: "Fully-configurable",
      duration: 474,
      genre: "Pop"
    }
  ];
  
  
  module.exports = entireCatalog